name: Step 2 - NetBird

on:
  workflow_call:

jobs:
  netbird:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download VM IP
        uses: actions/download-artifact@v4
        with:
          name: vm-ip

      - name: Read IP
        run: echo "IP=$(cat 1-infra/ip.txt)" >> $GITHUB_ENV

      - name: Setup SSH key (if needed)
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H $IP >> ~/.ssh/known_hosts

      - name: Install NetBird
        run: |
          ssh -o StrictHostKeyChecking=no vennecy@$IP << 'EOF'
            sudo apt update -y
            sudo apt install -y curl

            curl -fsSL https://pkgs.netbird.io/install.sh | bash

            sudo netbird up
          EOF